print("we have to print these lines")
print("this is \\\\ backlash")
print("this is /\\/\\/\\ mounatain")
print("he is\tawesome(use escape sequence intade of many spaces)")
print("\\\"\\n \\t \'")